### PR TITLE
Fix failure to submit queued items when an item's attempt is missing.

### LINKED ISSUE #606: quiz item submissions fail when an attempt is missing
When a quiz attempt relating to a submission cannot be found, the entire submission process fails.

### PR DESCRIPTION
**Pull request by nwp90**
Fixes #606.

### CODE REVIEW

File: lang/en/plagiarism_turnitin.php [hunk 1]
```diff
@@ -260,6 +260,7 @@
 $string['errorcode10'] = 'This file has not been submitted to Turnitin because there is a problem creating the class in Turnitin which is preventing submissions, please consult your API logs for further information';
 $string['errorcode11'] = 'This file has not been submitted to Turnitin because it is missing data';
 $string['errorcode12'] = 'This file has not been submitted to Turnitin because it belongs to an assignment in which the course was deleted. Row ID: ({$a->id}) | Course Module ID: ({$a->cm}) | User ID: ({$a->userid})';
+$string['errorcode13'] = 'This file has not been submitted to Turnitin because the attempt it belongs to could not be found';
```
Comment (dwinn) [inline lang/en/plagiarism_turnitin.php:263]: This should be errorcode14 as there is already a 13.

File: lib.php [hunk 2]
```diff
@@ -3138,7 +3138,13 @@ function plagiarism_turnitin_send_queued_submissions() {
                 }
 
                 require_once($CFG->dirroot . '/mod/quiz/locallib.php');
-                $attempt = quiz_attempt::create($queueditem->itemid);
+                try {
+                    $attempt = quiz_attempt::create($queueditem->itemid);
+                } catch (Exception $e) {
+                    plagiarism_turnitin_activitylog(get_string('errorcode13', 'plagiarism_turnitin'), "PP_NO_ATTEMPT");
+                    $errorcode = 13;
```
Comment (dwinn) [inline lib.php:3145]: This should be errorcode14 as there is already a 13.

**Comment by dwinn** [comment]
Thanks for the contribution @nwp90. I am going to merge this and then do a further commit to develop to change the errorcode to 14, as I don't think I'll be able to commit a change to your branch since it's on a fork. I'm testing this issue now as we're planning to release a fix for it soon.
